util:
  encrypt:
    passcode: password
    algorithm: algorithm1

spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.100.212:1521:ORCL
    username: aimframework
    password: aim#2022
    driver-class-name: oracle.jdbc.driver.OracleDriver